apiVersion: v1
kind: Namespace
metadata:
  name: my-rabbitmq
---
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: my-rabbitmq-cluster
  namespace: my-rabbitmq
spec:
  persistence:
    storage: 20Gi
